### ISSUE TITLE
Unable to 'make examples' due to Makefile errors + inclusion errors

### ISSUE THREAD

**Issue by abraunegg** [dlang-community/dfuse#4]
I am attempting to following the directions to build the examples as per: https://github.com/dlang-community/dfuse#examples, however the following initial error is thrown:
```
(dmd-2.093.1)[alex@centos7full dfuse]$ make examples
make: *** No rule to make target `source/c/fuse/common.d', needed by `simplefs'.  Stop.
(dmd-2.093.1)[alex@centos7full dfuse]$ 
```

If the Makefile is then updated to read:
```
sources = source/c/fuse/fuse.d source/c/fuse/fuse_common.d source/dfuse/fuse.d
```

building the example binary still fails, but goes a little further:
```
(dmd-2.093.1)[alex@centos7full dfuse]$ make examples
dmd -w -debug -g -L-lfuse -ofsimplefs example/simplefs.d source/c/fuse/fuse.d source/c/fuse/fuse_common.d source/dfuse/fuse.d
source/c/fuse/fuse_common.d(11): Error: module fuse_opt is in file 'c/fuse/fuse_opt.d' which cannot be read
import path[0] = /home/alex/dlang/dmd-2.093.1/linux/bin64/../../src/phobos
import path[1] = /home/alex/dlang/dmd-2.093.1/linux/bin64/../../src/druntime/import
make: *** [simplefs] Error 1
(dmd-2.093.1)[alex@centos7full dfuse]$ 
```

Is it possible for you to update the project so that the examples can be built - or is there something else which I am missing?

**Comment by CyberShadow** [comment]
Sorry for missing this when it was posted,

https://github.com/dlang-community/dfuse/pull/5 addresses this (by replacing the Makefile with working Dub configuration, which is a much more idiomatic way to build D code).

The example is now also tested that it is buildable on Linux and macOS.

**Comment by CyberShadow** [comment]
#5 was merged, so I think we can close this.
